spring:
  profiles:
    active: dev

---

server:
  port: 6001

spring:
  profiles: dev
  application:
    name: springcloud_dev

eureka:
  client:
    service-url:
        defaultZone: http://localhost:7001/eureka/
